// <auto-generated />
using System;
using FSDE_Oct_24_3_ru_AWS_Test_Products.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSDE_Oct_24_3_ru_AWS_Test_Products.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSDE_Oct_24_3_ru_AWS_Test_Products.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest Apple smartphone with A17 Pro chip",
                            Name = "iPhone 15 Pro",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flagship Android smartphone by Samsung",
                            Name = "Samsung Galaxy S24",
                            Price = 1099.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            CreatedAt = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Powerful laptop for developers and designers",
                            Name = "Dell XPS 15",
                            Price = 1899.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium wireless productivity mouse",
                            Name = "Logitech MX Master 3S",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RGB mechanical keyboard for gaming and work",
                            Name = "Mechanical Keyboard K8",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Audio",
                            CreatedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise cancelling premium headphones",
                            Name = "Sony WH-1000XM5",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Wearables",
                            CreatedAt = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smartwatch with health tracking features",
                            Name = "Apple Watch Series 9",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Cameras",
                            CreatedAt = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Action camera for adventures and blogging",
                            Name = "GoPro Hero 12",
                            Price = 450.75m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Next-gen gaming console by Sony",
                            Name = "PlayStation 5",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Books",
                            CreatedAt = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable e-book reader with backlight",
                            Name = "Amazon Kindle Paperwhite",
                            Price = 159.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
